<?php
// src/Service/UserManager.php
namespace App\Service;

use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\DependencyInjection\ContainerInterface as Container;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\Config\Definition\Exception\Exception;

//use Symfony\Component\Validator\Constraints\DateTime;

class UserManager extends Controller
{
    protected $container;
    private $encoder;
    private $mailer;
    private $em;

    public function __construct(
        Container $container,
        UserPasswordEncoderInterface $encoder,
        \Swift_Mailer $mailer
    ) {
        $this->container = $container;
        $this->encoder = $encoder;
        $this->mailer = $mailer;
        $this->em = $this->getDoctrine()->getManager();
    }

    /**
     * @return string
     */
    /*
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
    */

    // Inserts or updates a user into the database.
    public function saveUserToDB(User $user)
    {
        $this->em->persist($user);
        $this->em->flush();
    }

    // Deletes a user from the database.
    public function deleteUserFromDB(User $user)
    {
        $this->em->remove($user);
        $this->em->flush();
    }

    // Initializes the login form.
    public function initLoginForm(AuthenticationUtils $authenticationUtils)
    {
        // dernier identifiant de connexion utilisé
        $lastUsername = $authenticationUtils->getLastUsername();
        // erreur d'authentification (s'il y en a une)
        $error = $authenticationUtils->getLastAuthenticationError();

        return [
            'lastUsername' => $lastUsername,
            'error' => $error,
        ];
    }
}
