swiftmailer:
    transport:        "%swiftmailer_transport%"
    username:         "%swiftmailer_username%"
    password:         "%swiftmailer_password%"
    host:             "%swiftmailer_host%"
    port:             "%swiftmailer_port%"
    encryption:       "%swiftmailer_encryption%"
    auth-mode:        "%swiftmailer_auth-mode%"
    spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false
