<?php

// src/Controller/UserController.php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
//use App\Form\FormType;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use App\Service\UserManager;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class UserController extends Controller
{
    private $userManager;

    public function __construct(UserManager $userManager, LoggerInterface $logger)
    {
        $this->userManager = $userManager;
        $this->logger = $logger;
    }

    /**
     * User registration form.
     *
     * @Route("/registration", name="user_registration")
     */
    public function add(Request $request, LoggerInterface $logger)
    {
        $session = $request->getSession();

        // On crée un objet User
        $user = new User();

        // On crée le formulaire
        $form = $this->createForm(UserType::class, $user);

        /*$flashBag = "";
        foreach ($session->getFlashBag()->all() as $type => $messages) {
        foreach ($messages as $message) {
        $flashBag .= '<div class="flash-' . $type . '">' . $message . '</div>';
        }
        }*/

        // Si la requête est en POST
        if ($request->isMethod('POST')) {
            // À partir de maintenant, la variable $user contient les valeurs entrées dans le formulaire par le visiteur
            $form->handleRequest($request);

            // On vérifie que les valeurs entrées sont correctes
            if ($form->isValid()) {
                if (true === $this->userManager->persistUser($user, $request)) {
                    if (true === $this->userManager->sendValidationEmail($user, $request)) {
                        /*return $this->render('index.html.twig', array(
                        'nom' => 'dev',
                        'flashBag' => $flashBag
                        ));*/
                        return $this->redirectToRoute('homepage');
                    } else {
                        /*return $this->render('user/add.html.twig', array(
                        'form' => $form->createView(),
                        'flashBag' => $flashBag,
                        ));*/
                        return $this->redirectToRoute('user_registration');
                    }
                } else {
                    return $this->redirectToRoute('user_login');
                }
            }
        }

        // À ce stade, le formulaire n'est pas valide car :
        // - Soit la requête est de type GET, donc le visiteur vient d'arriver sur la page et veut voir le formulaire
        // - Soit la requête est de type POST, mais le formulaire contient des valeurs invalides, donc on l'affiche de nouveau

        return $this->render('user/add.html.twig', array(
            'form' => $form->createView(),
        ));
    }

    /**
     * User account validation.
     *
     * @Route("/registration-confirm", name="registration_confirm")
     */
    public function confirmAccount(Request $request)
    {
        if (true === $this->userManager->confirmUserRegistration($request)) {
            return $this->redirectToRoute('homepage');
        } else {
            return $this->redirectToRoute('user_registration');
        }
    }

    /**
     * User profile modification form.
     *
     * @Route("/edit-profile", name="user_profile_edition")
     */
    public function edit(Request $request/*,UserPasswordEncoderInterface $encoder*/)
    {
        // TODO
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    /**
     * @Route("/login", name="user_login")
     */
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        $data = $this->userManager->initLoginForm($authenticationUtils);

        return $this->render(
            'user/login.html.twig',
            [
                'last_username' => $data['lastUsername'],
                'error' => $data['error'],
            ]
        );
    }

    /**
     * @Route("/logout", name="user_logout")
     */
    public function logout(): void
    {
        throw new \Exception('This should never be reached!');
    }

    /**
     * Forgotten password.
     *
     * @Route("/forgotten-pwd", name="user_forgotten_pwd")
     */
    public function pwdForgotten(Request $request)
    {
        $this->logger->info('> > > > > > IN pwdForgotten < < < < < <');

        $session = $request->getSession();
        $em = $this->userManager;
        //$user = new User();
        $form = $this->createForm(FormType::class, null);

        if ($request->isMethod('POST')) {
            $this->logger->info('> > > > > > FORM POSTED < < < < < <');
            //if ($form->isSubmitted() && $form->isValid()) {
            //if ($form->isValid()) {
            if (true) {
                $this->logger->info('> > > > > > FORM VALID < < < < < <');
                $email = $request->request->get('email');
                if (null !== $user = $em->getUserByEmail($email, $request)) {
                    if (true === $em->sendPwdResetEmail($user, $request)) {
                        return $this->render('user/pwd-reset-email-sent.html.twig', array());
                    } else {
                        return $this->redirectToRoute('user_forgotten_pwd');
                    }
                }
            }
        }
        return $this->render('user/forgotten-pwd-step1.twig', array());
    }

    /**
     * User password reset management.
     *
     * @Route("/registration-confirm", name="pwd_reset_confirm")
     */
    public function confirmPwdReset(Request $request)
    {
        if (true === $this->userManager->confirmPwdResetEmail($request)) {
            return $this->redirectToRoute('homepage');
        } else {
            return $this->redirectToRoute('user_forgotten_pwd');
        }
    }

    /**
     * Forgotten password.
     *
     * @Route("/new-pwd", name="user_new_pwd")
     */
    public function userNewPdw(Request $request)
    {
        $session = $request->getSession();

        if ($request->isMethod('POST')) {
            if ($form->isValid()) {
                $pwd1 = $request->request->get('pwd1');
                $pwd2 = $request->request->get('pwd2');
                if (true === $this->userManager->checkNewPdw($pwd1, $pwd2)) {
                    /* message : pwd reset successfully */
                    return $this->redirectToRoute('user_login');
                } else {
                    /* message : pwd reset failure */
                    return $this->render('user/forgotten-pwd-step2.twig', array());
                }
            }
        }
        return $this->render('user/forgotten-pwd-step2.twig', array());
    }

}
